### ISSUE TITLE
 Failed to resolve entry for package "@coremedia-labs/preview-integration"

### ISSUE THREAD

**Issue by sravancm** [CoreMedia/coremedia-headless-client-react#31]
**Describe the bug**
unable to start spark application due to bug in package

**To Reproduce**
1. navigate to spark folder 
2. pnpm install
3. pnpm build 
error is thrown
 Failed to resolve entry for package "@coremedia-labs/preview-integration

**Expected behavior**
spark application should open with 
http://localhost:5173/

**Screenshots**
![5173](https://github.com/CoreMedia/coremedia-headless-client-react/assets/119657663/c2602a40-1aa9-4c6f-9f73-dc80985e3ce2)

**Detailed Log :**
[plugin:vite:import-analysis] Failed to resolve entry for package "@coremedia-labs/preview-integration". The package may have incorrect main/module/exports specified in its package.json.
/Users/spalakal/Documents/Projects/spark-ws-11/coremedia-headless-client-react/apps/spark/src/index.tsx
    at packageEntryFailure (file:///Users/spalakal/Documents/Projects/spark-ws-11/coremedia-headless-client-react/node_modules/.pnpm/vite@4.5.0_@types+node@18.18.6/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28725:11)
    at resolvePackageEntry (file:///Users/spalakal/Documents/Projects/spark-ws-11/coremedia-headless-client-react/node_modules/.pnpm/vite@4.5.0_@types+node@18.18.6/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28722:5)
    at tryNodeResolve (file:///Users/spalakal/Documents/Projects/spark-ws-11/coremedia-headless-client-react/node_modules/.pnpm/vite@4.5.0_@types+node@18.18.6/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28453:20)
    at Context.resolveId (file:///Users/spalakal/Documents/Projects/spark-ws-11/coremedia-headless-client-react/node_modules/.pnpm/vite@4.5.0_@types+node@18.18.6/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28212:28)
    at async Object.resolveId (file:///Users/spalakal/Documents/Projects/spark-ws-11/coremedia-headless-client-react/node_modules/.pnpm/vite@4.5.0_@types+node@18.18.6/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44276:32)
    at async TransformContext.resolve (file:///Users/spalakal/Documents/Projects/spark-ws-11/coremedia-headless-client-react/node_modules/.pnpm/vite@4.5.0_@types+node@18.18.6/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:43992:23)
    at async normalizeUrl (file:///Users/spalakal/Documents/Projects/spark-ws-11/coremedia-headless-client-react/node_modules/.pnpm/vite@4.5.0_@types+node@18.18.6/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:41836:34)
    at async file:///Users/spalakal/Documents/Projects/spark-ws-11/coremedia-headless-client-react/node_modules/.pnpm/vite@4.5.0_@types+node@18.18.6/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:41998:47
    at async Promise.all (index 5)
    at async TransformContext.transform (file:///Users/spalakal/Documents/Projects/spark-ws-11/coremedia-headless-client-react/node_modules/.pnpm/vite@4.5.0_@types+node@18.18.6/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:41914:13

**Desktop (please complete the following information):**
 - OS: [MAC os M1]
 - Browser [e.g. chrome]
 - Version [cm 11, 2307.1]

**Additional context**
 stitching and mocking both servers are up and running
stitching server log:
2023-11-28 16:48:04 [INFO]  Fetching schemas from GraphQL endpoints
2023-11-28 16:48:04 [INFO]  Loading schema from http://localhost:41180/graphql (Headless Server).
2023-11-28 16:48:08 [INFO]  Successfully loaded schema from coreMediaHeadlessServerEndpoint.
2023-11-28 16:48:08 [INFO]  Loading schema from http://localhost:43180/graphql (Headless Commerce Server).
2023-11-28 16:48:08 [INFO]  Successfully loaded schema from commerceCatalogEndpoint.
2023-11-28 16:48:08 [INFO]  Campaign Service not configured.
2023-11-28 16:48:08 [INFO]  Stitching server started on: http://localhost:4000/graphql

mocking server log:
> @coremedia-labs/headless-server-mocking@1.0.0 start /Users/spalakal/Documents/Projects/spark-ws-11/coremedia-headless-client-react/servers/mocking
> node ./bin/smoke -o all -d 10 mocks

2023-11-28 16:48:15 [INFO]  Mocking server started on: http://localhost:5000

**Comment by sravancm** [comment]
@mbuse could please check details and let me know anything missing

**Comment by pitgrap** [comment]
Hi @sravancm, this workspace is a multirepo. You always need to do these steps in the root folder:
1. pnpm install
2.  pnpm build

See https://github.com/CoreMedia/coremedia-headless-client-react#quickstart
